{{- if .Values.cluster.enabled }}
{{- if .Values.cluster.rbac.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cluster.rbacName" . }}
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cluster.rbacName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
