{{- if .Values.cluster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kobs.fullname" . }}-cluster
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
spec:
  replicas: {{ .Values.cluster.replicas }}
  selector:
    matchLabels:
      {{- include "kobs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cluster
  template:
    metadata:
      labels:
        {{- include "kobs.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cluster
        {{- with .Values.cluster.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cluster/configmap.yaml") . | sha256sum }}
        {{- with .Values.cluster.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cluster.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.cluster.podSecurityContext | nindent 8 }}
      containers:
        - name: cluster
          securityContext:
            {{- toYaml .Values.cluster.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - cluster
          {{- with .Values.cluster.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cluster.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-api
              containerPort: 15221
              protocol: TCP
            - name: http-metrics
              containerPort: 15222
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http-api
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: http-api
            failureThreshold: 3
          resources:
            {{- toYaml .Values.cluster.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /kobs/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- if .Values.cluster.volumeMounts }}
            {{- toYaml .Values.cluster.volumeMounts | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 90
      volumes:
        - name: config
          configMap:
            name: {{ include "kobs.fullname" . }}-cluster
        {{- if .Values.cluster.volumes }}
        {{- toYaml .Values.cluster.volumes | nindent 8 }}
        {{- end }}
      {{- with .Values.cluster.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cluster.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cluster.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cluster.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
