{{- if .Values.cluster.enabled }}
{{- if .Values.cluster.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster.serviceAccountName" . }}
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
{{- end }}
{{- end }}
