{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobs.fullname" . }}-cluster
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
    {{- with .Values.cluster.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.cluster.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.cluster.service.type }}
  ports:
    - port: 15221
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 15222
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "kobs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
{{- end }}
