// Code generated by mockery v2.9.4. DO NOT EDIT.

package instance

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockInstance is an autogenerated mock type for the Instance type
type MockInstance struct {
	mock.Mock
}

// GetLogs provides a mock function with given fields: ctx, query, timeStart, timeEnd
func (_m *MockInstance) GetLogs(ctx context.Context, query string, timeStart int64, timeEnd int64) (*Data, error) {
	ret := _m.Called(ctx, query, timeStart, timeEnd)

	var r0 *Data
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) *Data); ok {
		r0 = rf(ctx, query, timeStart, timeEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, query, timeStart, timeEnd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetName provides a mock function with given fields:
func (_m *MockInstance) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
