// Code generated by MockGen. DO NOT EDIT.
// Source: costmanagement.go

// Package costmanagement is a generated GoMock package.
package costmanagement

import (
	context "context"
	reflect "reflect"

	armcostmanagement "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/costmanagement/armcostmanagement"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetActualCosts mocks base method.
func (m *MockClient) GetActualCosts(ctx context.Context, scope string, timeStart, timeEnd int64) (*armcostmanagement.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActualCosts", ctx, scope, timeStart, timeEnd)
	ret0, _ := ret[0].(*armcostmanagement.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActualCosts indicates an expected call of GetActualCosts.
func (mr *MockClientMockRecorder) GetActualCosts(ctx, scope, timeStart, timeEnd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActualCosts", reflect.TypeOf((*MockClient)(nil).GetActualCosts), ctx, scope, timeStart, timeEnd)
}
