version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/cmd/kobs"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    groups:
      npm:
        patterns:
          - "*"
