run:
  timeout: 10m

  skip-dirs:
    - ./.git
    - ./.github
    - ./.vscode
    - ./app
    - ./bin
    - ./deploy
    - ./docs
    - ./pkg/cluster/kubernetes/clients

linters:
  disable-all: true
  enable:
    - bodyclose
    # - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - noctx
    - staticcheck
    - typecheck
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/kobsio/kobs
