---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kobs
  labels:
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
subjects:
  - kind: ServiceAccount
    name: kobs
    namespace: observability
roleRef:
  kind: ClusterRole
  name: kobs
  apiGroup: rbac.authorization.k8s.io
