---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kobs
  namespace: kobs
  labels:
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
data:
  config.yaml: |
    clusters:
      providers:
        - provider: incluster
          incluster:
            name: kobs
