---
apiVersion: v1
kind: Service
metadata:
  name: kobs
  namespace: observability
  labels:
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
spec:
  type: ClusterIP
  ports:
    - port: 15219
      targetPort: http-web
      protocol: TCP
      name: http-web
    - port: 15220
      targetPort: grpc-api
      protocol: TCP
      name: grpc-api
    - port: 15221
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    - port: 15222
      targetPort: http-envoy
      protocol: TCP
      name: http-envoy
  selector:
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
