---
# Source: kobs/templates/cluster/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kobs-cluster
  labels:
    helm.sh/chart: kobs-0.1.0
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
    app.kubernetes.io/version: "v0.12.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cluster
subjects:
  - kind: ServiceAccount
    name: kobs-cluster
    namespace: kobs
roleRef:
  kind: ClusterRole
  name: kobs-cluster
  apiGroup: rbac.authorization.k8s.io
