---
# Source: kobs/templates/cluster/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kobs-cluster
  labels:
    helm.sh/chart: kobs-0.1.0
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
    app.kubernetes.io/version: "v0.12.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cluster
