version: '3'
services:
  kobs-satellite:
    container_name: kobs-satellite
    build:
      context: ../../
      dockerfile: ./cmd/kobs/Dockerfile
    image: kobs
    volumes:
      - ./kobs/satellite.yaml:/kobs/config.yaml
      - $HOME/.kube/config:/.kube/config
    ports:
      - 15221:15221
    command:
      - satellite
      - --log.level=debug
      - --satellite.token=unsecuretoken
  kobs-hub:
    container_name: kobs-hub
    depends_on:
      - kobs-satellite
    image: kobs
    volumes:
      - ./kobs/hub.yaml:/kobs/config.yaml
    ports:
      - 15219:15219
      - 15220:15220
    command:
      - hub
      - --log.level=debug
