version: '3'
services:
  kobs:
    container_name: kobs
    build:
      context: .
      dockerfile: ./cmd/kobs/Dockerfile
    image: kobs
    volumes:
      - ./kobs/config.yaml:/kobs/config.yaml
      - $HOME/.kube/config:/.kube/config
    ports:
      - 15219:15219
      - 15220:15220
      - 15221:15221
    command:
      --log.level=trace
