---
apiVersion: kobs.io/v1
kind: Application
metadata:
  name: details
  namespace: bookinfo
spec:
  description: The details microservice contains book information.
  tags:
    - bookinfo
  links:
    - title: Website
      link: https://istio.io/latest/docs/examples/bookinfo/
    - title: GitHub
      link: https://github.com/istio/istio/tree/master/samples/bookinfo
    - title: Application CR
      link: https://github.com/kobsio/kobs/blob/main/deploy/demo/kobs/base/crs/applications/details.yaml
  teams:
    - cod@kobs.io
  insights:
    - title: Success Rate
      type: sparkline
      unit: "%"
      plugin:
        name: prometheus
        type: prometheus
        options:
          query: sum(irate(istio_requests_total{reporter="destination",destination_workload_namespace=~"bookinfo",destination_workload=~"details-v1",response_code!~"5.*"}[5m])) / sum(irate(istio_requests_total{reporter="destination",destination_workload_namespace=~"bookinfo",destination_workload=~"details-v1"}[5m])) * 100
    - title: Healthy Replicas
      type: sparkline
      unit: "%"
      plugin:
        name: prometheus
        type: prometheus
        options:
          query: kube_deployment_status_replicas{namespace="bookinfo", deployment=~"details.*"} / kube_deployment_spec_replicas{namespace="bookinfo", deployment=~"details.*"} * 100
  dashboards:
    - title: Overview
      inline:
        rows:
          - size: 1
            panels:
              - title: Desired Replicas
                colSpan: 3
                plugin:
                  name: prometheus
                  type: prometheus
                  options:
                    type: sparkline
                    queries:
                      - query: kube_deployment_spec_replicas{namespace="bookinfo", deployment=~"details.*"}
              - title: Current Replicas
                colSpan: 3
                plugin:
                  name: prometheus
                  type: prometheus
                  options:
                    type: sparkline
                    queries:
                      - query: kube_deployment_status_replicas{namespace="bookinfo", deployment=~"details.*"}
              - title: Updated Replicas
                colSpan: 3
                plugin:
                  name: prometheus
                  type: prometheus
                  options:
                    type: sparkline
                    queries:
                      - query: kube_deployment_status_replicas_updated{namespace="bookinfo", deployment=~"details.*"}
              - title: Available Replicas
                colSpan: 3
                plugin:
                  name: prometheus
                  type: prometheus
                  options:
                    type: sparkline
                    queries:
                      - query: kube_deployment_status_replicas_available{namespace="bookinfo", deployment=~"details.*"}
          - size: -1
            panels:
              - title: Workloads
                plugin:
                  name: resources
                  type: app
                  options:
                    satellites:
                      - kobs
                    clusters:
                      - kobs
                    namespaces:
                      - bookinfo
                    resources:
                      - pods
                      - deployments
                      - services
                    selector: app=details
          - size: 2
            panels:
              - title: Open Alerts
                colSpan: 6
                plugin:
                  name: opsgenie
                  type: opsgenie
                  options:
                    type: alerts
                    queries:
                      - 'status: open AND namespace: "bookinfo"'
                      - 'status: closed AND namespace: "bookinfo"'
                    interval: 31536000
              - title: Topology
                colSpan: 6
                plugin:
                  name: topology
                  type: app
                  options:
                    satellite: "<% $.satellite %>"
                    cluster: "<% $.cluster %>"
                    namespace: "<% $.namespace %>"
                    name: "<% $.name %>"

    - name: resource-usage
      namespace: kobs
      title: Resource Usage
      placeholders:
        namespace: bookinfo
        pod: "details-.*-.*-.*"

    - name: istio-http
      namespace: kobs
      title: Istio HTTP Metrics
      placeholders:
        namespace: bookinfo
        app: details

    - title: Logs
      inline:
        rows:
          - size: -1
            panels:
              - title: Logs
                colSpan: 12
                plugin:
                  name: elasticsearch
                  type: elasticsearch
                  options:
                    showChart: true
                    queries:
                      - name: Pod Logs
                        query: "kubernetes.namespace: bookinfo AND kubernetes.labels.app: details"
                        fields:
                          - "kubernetes.container.name"
                          - "message"
                      - name: Istio Logs
                        query: "kubernetes.namespace: bookinfo AND kubernetes.labels.app: details AND kubernetes.container.name: istio-proxy AND _exists_: content.method"
                        fields:
                          - "kubernetes.pod.name"
                          - "content.authority"
                          - "content.route_name"
                          - "content.protocol"
                          - "content.method"
                          - "content.path"
                          - "content.response_code"
                          - "content.upstream_service_time"
                          - "content.bytes_received"
                          - "content.bytes_sent"

    - title: Traces
      inline:
        rows:
          - size: -1
            panels:
              - title: Traces
                colSpan: 12
                plugin:
                  name: jaeger
                  type: jaeger
                  options:
                    showChart: true
                    queries:
                      - name: All Requests
                        service: details.bookinfo
                      - name: Slow Requests
                        service: details.bookinfo
                        minDuration: 100ms
                      - name: Errors
                        service: details.bookinfo
                        tags: error=true
