---
apiVersion: kobs.io/v1
kind: Application
metadata:
  name: satellite
  namespace: kobs
spec:
  description: Kubernetes Observability Platform
  tags:
    - observability
    - kobs
    - kobs-satellite
  teams:
    - dia@kobs.io
  links:
    - title: Website
      link: https://kobs.io
    - title: GitHub
      link: https://github.com/kobsio/kobs
    - title: Application CR
      link: https://github.com/kobsio/kobs/blob/main/deploy/demo/kobs/crs/applications/satellite.yaml
  insights:
    - title: Success Rate
      type: sparkline
      unit: "%"
      plugin:
        name: prometheus
        type: prometheus
        options:
          query: sum(irate(istio_requests_total{reporter="destination",destination_workload_namespace=~"kobs",destination_workload=~"kobs-satellite",response_code!~"5.*"}[5m])) / sum(irate(istio_requests_total{reporter="destination",destination_workload_namespace=~"kobs",destination_workload=~"kobs-satellite"}[5m])) * 100
    - title: Healthy Replicas
      type: sparkline
      unit: "%"
      plugin:
        name: prometheus
        type: prometheus
        options:
          query: (sum(kube_deployment_status_replicas{namespace="kobs", deployment=~"satellite"}) / sum(kube_deployment_spec_replicas{namespace="kobs", deployment=~"satellite"})) * 100
  dashboards:
    - title: Overview
      inline:
        rows:
          - size: 1
            panels:
              - title: Desired Replicas
                colSpan: 3
                plugin:
                  name: prometheus
                  type: prometheus
                  options:
                    type: sparkline
                    queries:
                      - query: kube_deployment_spec_replicas{namespace="kobs", deployment="satellite"}
              - title: Current Replicas
                colSpan: 3
                plugin:
                  name: prometheus
                  type: prometheus
                  options:
                    type: sparkline
                    queries:
                      - query: kube_deployment_status_replicas{namespace="kobs", deployment="satellite"}
              - title: Updated Replicas
                colSpan: 3
                plugin:
                  name: prometheus
                  type: prometheus
                  options:
                    type: sparkline
                    queries:
                      - query: kube_deployment_status_replicas_updated{namespace="kobs", deployment="satellite"}
              - title: Available Replicas
                colSpan: 3
                plugin:
                  name: prometheus
                  type: prometheus
                  options:
                    type: sparkline
                    queries:
                      - query: kube_deployment_status_replicas_available{namespace="kobs", deployment="satellite"}
          - size: -1
            panels:
              - title: Workloads
                plugin:
                  name: resources
                  type: app
                  options:
                    satellites:
                      - kobs
                    clusters:
                      - kobs
                    namespaces:
                      - kobs
                    resources:
                      - pods
                      - deployments
                      - services
                    selector: app.kubernetes.io/name=satellite
          - size: 2
            panels:
              - title: Open Alerts
                colSpan: 6
                plugin:
                  name: opsgenie
                  type: opsgenie
                  options:
                    type: alerts
                    queries:
                      - 'status: open AND namespace: "kobs"'
                      - 'status: closed AND namespace: "kobs"'
                    interval: 31536000
              - title: Topology
                colSpan: 6
                plugin:
                  name: topology
                  type: app
                  options:
                    satellite: "<% $.satellite %>"
                    cluster: "<% $.cluster %>"
                    namespace: "<% $.namespace %>"
                    name: "<% $.name %>"

    - name: resource-usage
      namespace: kobs
      title: Resource Usage
      placeholders:
        namespace: kobs
        pod: "satellite-.*-.*"

    - name: istio-http
      namespace: kobs
      title: Istio HTTP Metrics
      placeholders:
        namespace: kobs
        app: kobs-satellite

    - title: Logs
      inline:
        rows:
          - size: -1
            panels:
              - title: Logs
                colSpan: 12
                plugin:
                  name: elasticsearch
                  type: elasticsearch
                  options:
                    showChart: true
                    queries:
                      - name: Pod Logs
                        query: "kubernetes.namespace: kobs AND kubernetes.labels.app: kobs-satellite"
                        fields:
                          - "kubernetes.container.name"
                          - "message"
                      - name: Istio Logs
                        query: "kubernetes.namespace: kobs AND kubernetes.labels.app: kobs-satellite AND kubernetes.container.name: istio-proxy AND _exists_: content.method"
                        fields:
                          - "kubernetes.pod.name"
                          - "content.authority"
                          - "content.route_name"
                          - "content.protocol"
                          - "content.method"
                          - "content.path"
                          - "content.response_code"
                          - "content.upstream_service_time"
                          - "content.bytes_received"
                          - "content.bytes_sent"

    - title: Traces
      inline:
        rows:
          - size: -1
            panels:
              - title: Traces
                colSpan: 12
                plugin:
                  name: jaeger
                  type: jaeger
                  options:
                    showChart: true
                    queries:
                      - name: All Requests
                        service: satellite
                      - name: Slow Requests
                        service: satellite
                        minDuration: 100ms
                      - name: Errors
                        service: satellite
                        tags: error=true
