apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kobs.fullname" . }}
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ tpl .Values.kobs.config . | indent 4 }}
