apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kobs.fullname" . }}
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "kobs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kobs.selectorLabels" . | nindent 8 }}
        {{- include "kobs.podLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "kobs.podAnnotations" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kobs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kobs
          securityContext:
            {{- toYaml .Values.kobs.securityContext | nindent 12 }}
          image: "{{ .Values.kobs.image.repository }}:{{ .Values.kobs.image.tag }}"
          imagePullPolicy: {{ .Values.kobs.image.pullPolicy }}
          args:
            - --api.auth.default-team={{ .Values.kobs.settings.auth.defaultTeam }}
            - --api.auth.enabled={{ .Values.kobs.settings.auth.enabled }}
            - --api.auth.header={{ .Values.kobs.settings.auth.header }}
            - --api.auth.interval={{ .Values.kobs.settings.auth.interval }}
            - --clusters.cache-duration.namespaces={{ .Values.kobs.settings.clustersCacheDurationNamespaces }}
            - --log.format={{ .Values.kobs.settings.logFormat }}
            - --log.level={{ .Values.kobs.settings.logLevel }}
          {{- with .Values.kobs.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-web
              containerPort: 15219
              protocol: TCP
            - name: http-api
              containerPort: 15220
              protocol: TCP
            - name: http-metrics
              containerPort: 15221
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http-api
          readinessProbe:
            httpGet:
              path: /api/health
              port: http-api
          resources:
            {{- toYaml .Values.kobs.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /kobs/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "kobs.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
