apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kobs.fullname" . }}
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "kobs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kobs.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kobs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kobs
          securityContext:
            {{- toYaml .Values.kobs.securityContext | nindent 12 }}
          image: "{{ .Values.kobs.image.repository }}:{{ .Values.kobs.image.tag }}"
          imagePullPolicy: {{ .Values.kobs.image.pullPolicy }}
          args:
            - --log.level={{ .Values.kobs.settings.logLevel }}
            - --log.format={{ .Values.kobs.settings.logFormat }}
          env:
            {{- with .Values.kobs.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http-web
              containerPort: 15219
              protocol: TCP
            - name: grpc-api
              containerPort: 15220
              protocol: TCP
            - name: http-metrics
              containerPort: 15221
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-web
          readinessProbe:
            httpGet:
              path: /health
              port: http-web
          resources:
            {{- toYaml .Values.kobs.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /kobs/config.yaml
              subPath: config.yaml
              readOnly: true
        {{ if .Values.envoy.enabled }}
        - name: envoy
          securityContext:
            {{- toYaml .Values.envoy.securityContext | nindent 12 }}
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          ports:
            - name: http-envoy
              containerPort: 15222
              protocol: TCP
            - name: http-admin
              containerPort: 9901
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-admin
          readinessProbe:
            httpGet:
              path: /ready
              port: http-admin
          resources:
            {{- toYaml .Values.envoy.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
              readOnly: true
        {{ end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kobs.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
