apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobs.fullname" . }}
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
    {{- include "kobs.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "kobs.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 15219
      targetPort: http-web
      protocol: TCP
      name: http-web
    - port: 15220
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 15221
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "kobs.selectorLabels" . | nindent 4 }}
