apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobs.fullname" . }}
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 15219
      targetPort: http-web
      protocol: TCP
      name: http-web
    - port: 15220
      targetPort: grpc-api
      protocol: TCP
      name: grpc-api
    - port: 15221
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    {{ if .Values.envoy.enabled }}
    - port: 15222
      targetPort: http-envoy
      protocol: TCP
      name: http-envoy
    {{ end }}
  selector:
    {{- include "kobs.selectorLabels" . | nindent 4 }}
