{{- if .Values.istio.virtualService.create -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "kobs.fullname" . }}
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
spec:
{{- with .Values.istio.virtualService.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.istio.virtualService.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
{{- end }}
  http:
    {{- toYaml .Values.istio.virtualService.additionalRoutes | nindent 4 }}
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: {{ include "kobs.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 15220
      timeout: {{ .Values.istio.virtualService.timeout }}
    - route:
        - destination:
            host: {{ include "kobs.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 15219
      timeout: 60s
{{- end }}
