{{- if .Values.hub.enabled }}
{{- if .Values.hub.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kobs.fullname" . }}-hub
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
spec:
  {{- toYaml .Values.hub.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      {{- include "kobs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: hub
{{- end }}
{{- end }}
