{{- if .Values.hub.enabled }}
{{- if .Values.hub.istio.virtualService.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "kobs.fullname" . }}-hub
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
    {{- with .Values.hub.istio.virtualService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.hub.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.hub.istio.virtualService.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.hub.istio.virtualService.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  http:
    {{- with .Values.hub.istio.virtualService.additionalRoutes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: {{ include "kobs.fullname" . }}-hub.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 15220
      timeout: {{ .Values.hub.istio.virtualService.timeout }}
      {{- with .Values.hub.istio.virtualService.headers }}
      headers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    - route:
        - destination:
            host: {{ include "kobs.fullname" . }}-hub.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 15219
      timeout: 60s
      {{- with .Values.hub.istio.virtualService.headers }}
      headers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
