---
apiVersion: kobs.io/v1alpha1
kind: Template
metadata:
  name: prometheus-kubernetes-resources-pod
spec:
  description: CPU, Memory and Network useage of a Pod via Prometheus.
  variables:
    - name: namespace
      description: "The Pod namespace. Can be set with the following JSONPath: '<< $.metadata.namespace >>'"
    - name: name
      description: "The Pod name. Can be set with the following JSONPath: '<< $.metadata.namespace >>'"
  plugin:
    name: Prometheus
    prometheus:
      variables:
        - name: Container
          label: container
          query: container_cpu_usage_seconds_total{namespace="<< namespace >>", image!="", pod="<< name >>", container!="POD", container!=""}
          allowAll: true
      charts:
        - title: CPU Usage
          type: area
          unit: Cores
          size: 12
          queries:
          - label: Current
            query: sum(max(rate(container_cpu_usage_seconds_total{namespace="<< namespace >>", image!="", pod="<< name >>", container=~"{{ .Container }}", container!="POD", container!=""}[2m])) by (container))
          - label: Requested
            query: sum(kube_pod_container_resource_requests{namespace="<< namespace >>", resource="cpu", pod="<< name >>", container=~"{{ .Container }}"})
          - label: Limit
            query: sum(kube_pod_container_resource_limits{namespace="<< namespace >>", resource="cpu", pod="<< name >>", container=~"{{ .Container }}"})
        - title: Memory Usage
          type: area
          unit: MiB
          size: 12
          queries:
          - label: Current
            query: sum(max(container_memory_working_set_bytes{namespace="<< namespace >>", pod="<< name >>", container=~"{{ .Container }}", container!="POD", container!=""}) by (container)) / 1024 / 1024
          - label: Requested
            query: sum(kube_pod_container_resource_requests{namespace="<< namespace >>", resource="memory", pod="<< name >>", container=~"{{ .Container }}"}) / 1024 / 1024
          - label: Limit
            query: sum(kube_pod_container_resource_limits{namespace="<< namespace >>", resource="memory", pod="<< name >>", container=~"{{ .Container }}"}) / 1024 / 1024

        - name: Network
          type: divider
        - title: Bandwidth
          type: area
          unit: bytes/s
          size: 12
          queries:
          - label: Received
            query: sum(irate(container_network_receive_bytes_total{namespace="<< namespace >>", pod="<< name >>"}[2m])) by (pod)
          - label: Transmitted
            query: -sum(irate(container_network_transmit_bytes_total{namespace="<< namespace >>", pod="<< name >>"}[2m])) by (pod)
        - title: Rate of Packets
          type: area
          unit: bytes/s
          size: 12
          queries:
          - label: Received
            query: sum(irate(container_network_receive_packets_total{namespace=~"<< namespace >>", pod=~"<< name >>"}[2m])) by (pod)
          - label: Transmitted
            query: -sum(irate(container_network_transmit_packets_total{namespace=~"<< namespace >>", pod=~"<< name >>"}[2m])) by (pod)
        - title: Rate of Packets Dropped
          type: area
          unit: bytes/s
          size: 12
          queries:
          - label: Received
            query: sum(irate(container_network_receive_packets_dropped_total{namespace=~"<< namespace >>", pod=~"<< name >>"}[2m])) by (pod)
          - label: Transmitted
            query: -sum(irate(container_network_transmit_packets_dropped_total{namespace=~"<< namespace >>", pod=~"<< name >>"}[2m])) by (pod)

        - name: Restarts
          type: divider
        - title: Restarts
          type: area
          size: 12
          queries:
          - label: Restarts
            query: max(kube_pod_container_status_restarts_total{namespace="<< namespace >>", pod="<< name >>", container=~"{{ .Container }}"})
