---
apiVersion: kobs.io/v1alpha1
kind: Template
metadata:
  name: prometheus-istio-workload-tcp
spec:
  description: Istio Workload Dashboard for TCP traffic, similar to the one provided for Grafana https://grafana.com/grafana/dashboards/7630.
  variables:
    - name: namespace
      description: The workload namespace.
    - name: workload
      description: The workload name.
  plugin:
    name: Prometheus
    prometheus:
      variables:
        - name: Reporter
          label: reporter
          query: istio_tcp_sent_bytes_total{destination_workload="<< workload >>", destination_workload_namespace=~"<< namespace >>"}
          allowAll: false
        - name: Source Workload Namespace
          label: source_workload_namespace
          query: istio_tcp_sent_bytes_total{reporter="{{ .Reporter }}", destination_workload="<< workload >>", destination_workload_namespace=~"<< namespace >>"}
          allowAll: true
        - name: Source Workload
          label: source_workload
          query: istio_tcp_sent_bytes_total{reporter="{{ .Reporter }}", destination_workload="<< workload >>", destination_workload_namespace=~"<< namespace >>", source_workload_namespace=~"{{ index . "Source Workload Namespace" }}"}
          allowAll: true
        - name: Destination Service
          label: destination_service
          query: istio_tcp_sent_bytes_total{reporter="source", source_workload=~"<< workload >>", source_workload_namespace=~"<< namespace >>"}
          allowAll: true
      charts:
        - title: TCP Server Traffic
          type: sparkline
          unit: bytes
          size: 6
          queries:
            - label: TCP Server Traffic
              query: sum(irate(istio_tcp_sent_bytes_total{reporter="{{ .Reporter }}", destination_workload_namespace=~"<< namespace >>", destination_workload=~"<< workload >>"}[1m])) + sum(irate(istio_tcp_received_bytes_total{reporter="{{ .Reporter }}", destination_workload_namespace=~"<< namespace >>", destination_workload=~"<< workload >>"}[1m]))
        - title: TCP Client Traffic
          type: sparkline
          unit: bytes
          size: 6
          queries:
            - label: TCP Client Traffic
              query: sum(irate(istio_tcp_sent_bytes_total{reporter="{{ .Reporter }}", source_workload_namespace=~"<< namespace >>", source_workload=~"<< workload >>"}[1m])) + sum(irate(istio_tcp_received_bytes_total{reporter="{{ .Reporter }}", source_workload_namespace=~"<< namespace >>", source_workload=~"<< workload >>"}[1m]))

        - title: Inbound Workloads
          type: divider
        - title: Bytes Received from Incoming TCP Connection
          type: line
          unit: bytes
          size: 6
          queries:
            - label: "{{ .source_workload }}.{{ .source_workload_namespace }} (🔐 mTLS)"
              query: round(sum(irate(istio_tcp_received_bytes_total{reporter="{{ .Reporter }}", connection_security_policy="mutual_tls", destination_workload_namespace=~"<< namespace >>", destination_workload=~"<< workload >>", source_workload=~"{{ index . "Source Workload" }}", source_workload_namespace=~"{{ index . "Source Workload Namespace" }}"}[1m])) by (source_workload, source_workload_namespace), 0.001)
            - label: "{{ .source_workload }}.{{ .source_workload_namespace }}"
              query: round(sum(irate(istio_tcp_received_bytes_total{reporter="{{ .Reporter }}", connection_security_policy!="mutual_tls", destination_workload_namespace=~"<< namespace >>", destination_workload=~"<< workload >>", source_workload=~"{{ index . "Source Workload" }}", source_workload_namespace=~"{{ index . "Source Workload Namespace" }}"}[1m])) by (source_workload, source_workload_namespace), 0.001)
        - title: Bytes Sent to Incoming TCP Connection
          type: line
          unit: bytes
          size: 6
          queries:
            - label: "{{ .source_workload }}.{{ .source_workload_namespace }} (🔐 mTLS)"
              query: round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy="mutual_tls", reporter="{{ .Reporter }}", destination_workload_namespace=~"<< namespace >>", destination_workload=~"<< workload >>", source_workload=~"{{ index . "Source Workload" }}", source_workload_namespace=~"{{ index . "Source Workload Namespace" }}"}[1m])) by (source_workload, source_workload_namespace), 0.001)
            - label: "{{ .source_workload }}.{{ .source_workload_namespace }}"
              query: round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!="mutual_tls", reporter="{{ .Reporter }}", destination_workload_namespace=~"<< namespace >>", destination_workload=~"<< workload >>", source_workload=~"{{ index . "Source Workload" }}", source_workload_namespace=~"{{ index . "Source Workload Namespace" }}"}[1m])) by (source_workload, source_workload_namespace), 0.001)

        - title: Outbound Workloads
          type: divider
        - title: Bytes Sent on Outgoing TCP Connection
          type: line
          unit: bytes
          size: 6
          queries:
            - label: "{{ .destination_service }} (🔐 mTLS)"
              query: round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy="mutual_tls", reporter="source", source_workload_namespace=~"<< namespace >>", source_workload=~"<< workload >>", destination_service=~"{{ index . "Destination Service" }}"}[1m])) by (destination_service), 0.001)
            - label: "{{ .destination_service }}"
              query: round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!="mutual_tls", reporter="source", source_workload_namespace=~"<< namespace >>", source_workload=~"<< workload >>", destination_service=~"{{ index . "Destination Service" }}"}[1m])) by (destination_service), 0.001)
        - title: Bytes Received from Outgoing TCP Connection
          type: line
          unit: bytes
          size: 6
          queries:
            - label: "{{ .destination_service }} (🔐 mTLS)"
              query: round(sum(irate(istio_tcp_received_bytes_total{reporter="source", connection_security_policy="mutual_tls", source_workload_namespace=~"<< namespace >>", source_workload=~"<< workload >>", destination_service=~"{{ index . "Destination Service" }}"}[1m])) by (destination_service), 0.001)
            - label: "{{ .destination_service }}"
              query: round(sum(irate(istio_tcp_received_bytes_total{reporter="source", connection_security_policy!="mutual_tls", source_workload_namespace=~"<< namespace >>", source_workload=~"<< workload >>", destination_service=~"{{ index . "Destination Service" }}"}[1m])) by (destination_service), 0.001)

