{{- if .Values.istio.virtualService.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "satellite.fullname" . }}
  labels:
    {{- include "satellite.labels" . | nindent 4 }}
spec:
{{- with .Values.istio.virtualService.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.istio.virtualService.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
{{- end }}
  http:
    {{- toYaml .Values.istio.virtualService.additionalRoutes | nindent 4 }}
    - route:
        - destination:
            host: {{ include "satellite.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 15221
      timeout: {{ .Values.istio.virtualService.timeout }}
{{- end }}
