// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kiali.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using GetNamespacesRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetNamespacesRequest) DeepCopyInto(out *GetNamespacesRequest) {
	p := proto.Clone(in).(*GetNamespacesRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetNamespacesRequest. Required by controller-gen.
func (in *GetNamespacesRequest) DeepCopy() *GetNamespacesRequest {
	if in == nil {
		return nil
	}
	out := new(GetNamespacesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetNamespacesRequest. Required by controller-gen.
func (in *GetNamespacesRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetNamespacesResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetNamespacesResponse) DeepCopyInto(out *GetNamespacesResponse) {
	p := proto.Clone(in).(*GetNamespacesResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetNamespacesResponse. Required by controller-gen.
func (in *GetNamespacesResponse) DeepCopy() *GetNamespacesResponse {
	if in == nil {
		return nil
	}
	out := new(GetNamespacesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetNamespacesResponse. Required by controller-gen.
func (in *GetNamespacesResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Namespace within kubernetes types, where deepcopy-gen is used.
func (in *Namespace) DeepCopyInto(out *Namespace) {
	p := proto.Clone(in).(*Namespace)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopy() *Namespace {
	if in == nil {
		return nil
	}
	out := new(Namespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetGraphRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetGraphRequest) DeepCopyInto(out *GetGraphRequest) {
	p := proto.Clone(in).(*GetGraphRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGraphRequest. Required by controller-gen.
func (in *GetGraphRequest) DeepCopy() *GetGraphRequest {
	if in == nil {
		return nil
	}
	out := new(GetGraphRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetGraphRequest. Required by controller-gen.
func (in *GetGraphRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetGraphResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetGraphResponse) DeepCopyInto(out *GetGraphResponse) {
	p := proto.Clone(in).(*GetGraphResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGraphResponse. Required by controller-gen.
func (in *GetGraphResponse) DeepCopy() *GetGraphResponse {
	if in == nil {
		return nil
	}
	out := new(GetGraphResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetGraphResponse. Required by controller-gen.
func (in *GetGraphResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Elements within kubernetes types, where deepcopy-gen is used.
func (in *Elements) DeepCopyInto(out *Elements) {
	p := proto.Clone(in).(*Elements)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Elements. Required by controller-gen.
func (in *Elements) DeepCopy() *Elements {
	if in == nil {
		return nil
	}
	out := new(Elements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Elements. Required by controller-gen.
func (in *Elements) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NodeWrapper within kubernetes types, where deepcopy-gen is used.
func (in *NodeWrapper) DeepCopyInto(out *NodeWrapper) {
	p := proto.Clone(in).(*NodeWrapper)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeWrapper. Required by controller-gen.
func (in *NodeWrapper) DeepCopy() *NodeWrapper {
	if in == nil {
		return nil
	}
	out := new(NodeWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NodeWrapper. Required by controller-gen.
func (in *NodeWrapper) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using EdgeWrapper within kubernetes types, where deepcopy-gen is used.
func (in *EdgeWrapper) DeepCopyInto(out *EdgeWrapper) {
	p := proto.Clone(in).(*EdgeWrapper)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeWrapper. Required by controller-gen.
func (in *EdgeWrapper) DeepCopy() *EdgeWrapper {
	if in == nil {
		return nil
	}
	out := new(EdgeWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new EdgeWrapper. Required by controller-gen.
func (in *EdgeWrapper) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Node within kubernetes types, where deepcopy-gen is used.
func (in *Node) DeepCopyInto(out *Node) {
	p := proto.Clone(in).(*Node)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Node. Required by controller-gen.
func (in *Node) DeepCopy() *Node {
	if in == nil {
		return nil
	}
	out := new(Node)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Node. Required by controller-gen.
func (in *Node) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Edge within kubernetes types, where deepcopy-gen is used.
func (in *Edge) DeepCopyInto(out *Edge) {
	p := proto.Clone(in).(*Edge)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Edge. Required by controller-gen.
func (in *Edge) DeepCopy() *Edge {
	if in == nil {
		return nil
	}
	out := new(Edge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Edge. Required by controller-gen.
func (in *Edge) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ServiceName within kubernetes types, where deepcopy-gen is used.
func (in *ServiceName) DeepCopyInto(out *ServiceName) {
	p := proto.Clone(in).(*ServiceName)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceName. Required by controller-gen.
func (in *ServiceName) DeepCopy() *ServiceName {
	if in == nil {
		return nil
	}
	out := new(ServiceName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServiceName. Required by controller-gen.
func (in *ServiceName) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ProtocolTraffic within kubernetes types, where deepcopy-gen is used.
func (in *ProtocolTraffic) DeepCopyInto(out *ProtocolTraffic) {
	p := proto.Clone(in).(*ProtocolTraffic)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolTraffic. Required by controller-gen.
func (in *ProtocolTraffic) DeepCopy() *ProtocolTraffic {
	if in == nil {
		return nil
	}
	out := new(ProtocolTraffic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolTraffic. Required by controller-gen.
func (in *ProtocolTraffic) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SEInfo within kubernetes types, where deepcopy-gen is used.
func (in *SEInfo) DeepCopyInto(out *SEInfo) {
	p := proto.Clone(in).(*SEInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SEInfo. Required by controller-gen.
func (in *SEInfo) DeepCopy() *SEInfo {
	if in == nil {
		return nil
	}
	out := new(SEInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SEInfo. Required by controller-gen.
func (in *SEInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Response within kubernetes types, where deepcopy-gen is used.
func (in *Response) DeepCopyInto(out *Response) {
	p := proto.Clone(in).(*Response)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Response. Required by controller-gen.
func (in *Response) DeepCopy() *Response {
	if in == nil {
		return nil
	}
	out := new(Response)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Response. Required by controller-gen.
func (in *Response) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
