// Code generated by MockGen. DO NOT EDIT.
// Source: kubernetesservices.go

// Package kubernetesservices is a generated GoMock package.
package kubernetesservices

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ListManagedClusters mocks base method.
func (m *MockClient) ListManagedClusters(ctx context.Context, resourceGroup string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListManagedClusters", ctx, resourceGroup)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListManagedClusters indicates an expected call of ListManagedClusters.
func (mr *MockClientMockRecorder) ListManagedClusters(ctx, resourceGroup interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListManagedClusters", reflect.TypeOf((*MockClient)(nil).ListManagedClusters), ctx, resourceGroup)
}
