clusters:
  providers:
    - provider: kubeconfig
      kubeconfig:
        path: ${HOME}/.kube/config

plugins:
  resources:
    forbidden:
      - clusters:
          - "*"
        namespaces:
          - "*"
        resources:
          - "secrets"
        verbs:
          - "*"

  applications:
    cache:
      topologyDuration: 1m
      teamsDuration: 1m
      tagsDuration: 1m

  prometheus:
    - name: prometheus
      displayName: Prometheus
      description: Prometheus can be used for the metrics of your application.
      address: http://localhost:9090
      username:
      password:
      token:

  elasticsearch:
    - name: elasticsearch
      displayName: Elasticsearch
      description: Elasticsearch can be used for the logs of your application.
      address: http://localhost:9200
      username:
      password:
      token:

  jaeger:
    - name: jaeger
      displayName: Jaeger
      description: Jaeger can be used for the traces of your application.
      address: http://localhost:16686
      username:
      password:
      token:

  kiali:
    - name: kiali
      displayName: Kiali
      description: Service mesh management for Istio.
      address: http://localhost:20001
      username:
      password:
      token:
      traffic:
        degraded: 1
        failure: 5

  # opsgenie:
  #   - name: opsgenie
  #     displayName: Opsgenie
  #     description: On-call and alert management to keep services always on.
  #     apiUrl: api.eu.opsgenie.com
  #     apiKey: ${OPSGENIE_API_KEY}
  #     url: https://<mycompany>.app.eu.opsgenie.com

  klogs:
    - name: klogs
      displayName: klogs
      description: Fast, scalable and reliable logging using Fluent Bit, Kafka and ClickHouse.
      address: localhost:9000
      database: logs
      username: ${CLICKHOUSE_USERNAME}
      password: ${CLICKHOUSE_PASSWORD}
