clusters:
  providers:
    - provider: kubeconfig
      kubeconfig:
        # path: ${HOME}/.kube/config
        path: ${HOME}/Documents/kubeconfig/kubeconfig

plugins:
  resources:
    forbidden:
      - secrets

  applications:
    topologyCacheDuration: 1m
    teamsCacheDuration: 1m

  prometheus:
    - name: prometheus
      displayName: Prometheus
      description: Prometheus can be used for the metrics of your application.
      address: http://localhost:9090
      username:
      password:
      token:

elasticsearch:
  - name: Elasticsearch
    description: Elasticsearch can be used for the logs of your application.
    address: http://localhost:9200
    username:
    password:
    token:

jaeger:
  - name: Jaeger
    description: Jaeger can be used for the traces of your application.
    address: http://localhost:16686
    username:
    password:
    token:

kiali:
  - name: Kiali
    description: Service mesh management for Istio.
    address: http://localhost:20001
    username:
    password:
    token:
    traffic:
      degraded: 1
      failure: 5

# opsgenie:
#   - name: Opsgenie
#     description: On-call and alert management to keep services always on.
#     apiUrl: api.eu.opsgenie.com
#     apiKey: ${OPSGENIE_API_KEY}
