// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: prometheus.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using GetVariablesRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetVariablesRequest) DeepCopyInto(out *GetVariablesRequest) {
	p := proto.Clone(in).(*GetVariablesRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetVariablesRequest. Required by controller-gen.
func (in *GetVariablesRequest) DeepCopy() *GetVariablesRequest {
	if in == nil {
		return nil
	}
	out := new(GetVariablesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetVariablesRequest. Required by controller-gen.
func (in *GetVariablesRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetVariablesResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetVariablesResponse) DeepCopyInto(out *GetVariablesResponse) {
	p := proto.Clone(in).(*GetVariablesResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetVariablesResponse. Required by controller-gen.
func (in *GetVariablesResponse) DeepCopy() *GetVariablesResponse {
	if in == nil {
		return nil
	}
	out := new(GetVariablesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetVariablesResponse. Required by controller-gen.
func (in *GetVariablesResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetMetricsRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetMetricsRequest) DeepCopyInto(out *GetMetricsRequest) {
	p := proto.Clone(in).(*GetMetricsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMetricsRequest. Required by controller-gen.
func (in *GetMetricsRequest) DeepCopy() *GetMetricsRequest {
	if in == nil {
		return nil
	}
	out := new(GetMetricsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetMetricsRequest. Required by controller-gen.
func (in *GetMetricsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetMetricsResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetMetricsResponse) DeepCopyInto(out *GetMetricsResponse) {
	p := proto.Clone(in).(*GetMetricsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMetricsResponse. Required by controller-gen.
func (in *GetMetricsResponse) DeepCopy() *GetMetricsResponse {
	if in == nil {
		return nil
	}
	out := new(GetMetricsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetMetricsResponse. Required by controller-gen.
func (in *GetMetricsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MetricLookupRequest within kubernetes types, where deepcopy-gen is used.
func (in *MetricLookupRequest) DeepCopyInto(out *MetricLookupRequest) {
	p := proto.Clone(in).(*MetricLookupRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricLookupRequest. Required by controller-gen.
func (in *MetricLookupRequest) DeepCopy() *MetricLookupRequest {
	if in == nil {
		return nil
	}
	out := new(MetricLookupRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MetricLookupRequest. Required by controller-gen.
func (in *MetricLookupRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MetricLookupResponse within kubernetes types, where deepcopy-gen is used.
func (in *MetricLookupResponse) DeepCopyInto(out *MetricLookupResponse) {
	p := proto.Clone(in).(*MetricLookupResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricLookupResponse. Required by controller-gen.
func (in *MetricLookupResponse) DeepCopy() *MetricLookupResponse {
	if in == nil {
		return nil
	}
	out := new(MetricLookupResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MetricLookupResponse. Required by controller-gen.
func (in *MetricLookupResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetTableDataRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetTableDataRequest) DeepCopyInto(out *GetTableDataRequest) {
	p := proto.Clone(in).(*GetTableDataRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetTableDataRequest. Required by controller-gen.
func (in *GetTableDataRequest) DeepCopy() *GetTableDataRequest {
	if in == nil {
		return nil
	}
	out := new(GetTableDataRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetTableDataRequest. Required by controller-gen.
func (in *GetTableDataRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetTableDataResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetTableDataResponse) DeepCopyInto(out *GetTableDataResponse) {
	p := proto.Clone(in).(*GetTableDataResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetTableDataResponse. Required by controller-gen.
func (in *GetTableDataResponse) DeepCopy() *GetTableDataResponse {
	if in == nil {
		return nil
	}
	out := new(GetTableDataResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetTableDataResponse. Required by controller-gen.
func (in *GetTableDataResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Metrics within kubernetes types, where deepcopy-gen is used.
func (in *Metrics) DeepCopyInto(out *Metrics) {
	p := proto.Clone(in).(*Metrics)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metrics. Required by controller-gen.
func (in *Metrics) DeepCopy() *Metrics {
	if in == nil {
		return nil
	}
	out := new(Metrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Metrics. Required by controller-gen.
func (in *Metrics) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Data within kubernetes types, where deepcopy-gen is used.
func (in *Data) DeepCopyInto(out *Data) {
	p := proto.Clone(in).(*Data)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Data. Required by controller-gen.
func (in *Data) DeepCopy() *Data {
	if in == nil {
		return nil
	}
	out := new(Data)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Data. Required by controller-gen.
func (in *Data) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Row within kubernetes types, where deepcopy-gen is used.
func (in *Row) DeepCopyInto(out *Row) {
	p := proto.Clone(in).(*Row)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Row. Required by controller-gen.
func (in *Row) DeepCopy() *Row {
	if in == nil {
		return nil
	}
	out := new(Row)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Row. Required by controller-gen.
func (in *Row) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Spec within kubernetes types, where deepcopy-gen is used.
func (in *Spec) DeepCopyInto(out *Spec) {
	p := proto.Clone(in).(*Spec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spec. Required by controller-gen.
func (in *Spec) DeepCopy() *Spec {
	if in == nil {
		return nil
	}
	out := new(Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Spec. Required by controller-gen.
func (in *Spec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Variable within kubernetes types, where deepcopy-gen is used.
func (in *Variable) DeepCopyInto(out *Variable) {
	p := proto.Clone(in).(*Variable)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Variable. Required by controller-gen.
func (in *Variable) DeepCopy() *Variable {
	if in == nil {
		return nil
	}
	out := new(Variable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Variable. Required by controller-gen.
func (in *Variable) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Chart within kubernetes types, where deepcopy-gen is used.
func (in *Chart) DeepCopyInto(out *Chart) {
	p := proto.Clone(in).(*Chart)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Chart. Required by controller-gen.
func (in *Chart) DeepCopy() *Chart {
	if in == nil {
		return nil
	}
	out := new(Chart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Chart. Required by controller-gen.
func (in *Chart) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Query within kubernetes types, where deepcopy-gen is used.
func (in *Query) DeepCopyInto(out *Query) {
	p := proto.Clone(in).(*Query)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Query. Required by controller-gen.
func (in *Query) DeepCopy() *Query {
	if in == nil {
		return nil
	}
	out := new(Query)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Query. Required by controller-gen.
func (in *Query) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Column within kubernetes types, where deepcopy-gen is used.
func (in *Column) DeepCopyInto(out *Column) {
	p := proto.Clone(in).(*Column)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Column. Required by controller-gen.
func (in *Column) DeepCopy() *Column {
	if in == nil {
		return nil
	}
	out := new(Column)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Column. Required by controller-gen.
func (in *Column) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
