{{- if .Values.watcher.enabled }}
{{- if .Values.watcher.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hub.fullname" . }}-watcher
  labels:
    {{- include "hub.watcher.labels" . | nindent 4 }}
    {{- include "hub.watcher.serviceMonitorLabels" . | nindent 4 }}
spec:
  endpoints:
    - port: http-metrics
      {{- if .Values.watcher.serviceMonitor.interval }}
      interval: {{ .Values.watcher.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.watcher.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.watcher.serviceMonitor.scrapeTimeout }}
      {{- end }}
      path: /metrics
      honorLabels: {{ .Values.watcher.serviceMonitor.honorLabels }}
      {{- if .Values.watcher.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{ toYaml .Values.watcher.serviceMonitor.metricRelabelings | nindent 6 }}
      {{- end }}
      {{- if .Values.watcher.serviceMonitor.relabelings }}
      relabelings:
      {{ toYaml .Values.watcher.serviceMonitor.relabelings | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "hub.watcher.selectorLabels" . | nindent 6 }}
{{- end -}}
{{- end -}}
