---
# Source: kobs/templates/watcher/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kobs-watcher
  labels:
    helm.sh/chart: kobs-0.1.0
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
    app.kubernetes.io/version: "v0.12.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: watcher
spec:
  type: ClusterIP
  ports:
    - port: 15222
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
    app.kubernetes.io/component: watcher
