---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub
  namespace: kobs
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/instance: hub
data:
  config.yaml: |
    satellites:
      - name: kobs
        address: http://satellite.kobs.svc.cluster.local:15221
        token: unsecuretoken
