---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  namespace: kobs
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/instance: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hub
      app.kubernetes.io/instance: hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hub
        app.kubernetes.io/instance: hub
    spec:
      containers:
        - name: hub
          image: "kobsio/kobs:v0.8.0"
          imagePullPolicy: IfNotPresent
          args:
            - hub
            - --log.format=console
            - --log.level=info
            - --hub.mode=default
            - --hub.store.driver=bolt
            - --hub.store.uri=/tmp/kobs.db
            - --hub.watcher.interval=300s
            - --hub.watcher.worker=10
            - --auth.enabled=false
            - --auth.header.user=X-Auth-Request-Email
            - --auth.header.teams=X-Auth-Request-Groups
            - --auth.logout.redirect=/oauth2/sign_out
            - --auth.session.interval=48h0m0s
          ports:
            - name: http-web
              containerPort: 15219
              protocol: TCP
            - name: http-api
              containerPort: 15220
              protocol: TCP
            - name: http-metrics
              containerPort: 15222
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http-api
          readinessProbe:
            httpGet:
              path: /api/health
              port: http-api
          volumeMounts:
            - name: config
              mountPath: /kobs/config.yaml
              subPath: config.yaml
              readOnly: true
      terminationGracePeriodSeconds: 90
      volumes:
        - name: config
          configMap:
            name: hub
