---
# Source: kobs/templates/hub/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobs-hub
  labels:
    helm.sh/chart: kobs-0.1.0
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
    app.kubernetes.io/version: "v0.12.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kobs
      app.kubernetes.io/instance: kobs
      app.kubernetes.io/component: hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kobs
        app.kubernetes.io/instance: kobs
        app.kubernetes.io/component: hub
      annotations:
        checksum/config: 6a772fbdaa69f465410db25a090d8032a934f071bd8bdd0e443cad9753dcbdc9
    spec:
      securityContext:
        {}
      containers:
        - name: hub
          securityContext:
            {}
          image: "ghcr.io/kobsio/kobs:v0.12.0"
          imagePullPolicy: IfNotPresent
          args:
            - hub
          ports:
            - name: http-app
              containerPort: 15219
              protocol: TCP
            - name: http-api
              containerPort: 15220
              protocol: TCP
            - name: http-metrics
              containerPort: 15222
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http-api
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: http-api
            failureThreshold: 3
          resources:
            {}
          volumeMounts:
            - name: config
              mountPath: /kobs/config.yaml
              subPath: config.yaml
              readOnly: true
      terminationGracePeriodSeconds: 90
      volumes:
        - name: config
          configMap:
            name: kobs-hub
