---
apiVersion: v1
kind: Service
metadata:
  name: hub
  namespace: kobs
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/instance: hub
spec:
  type: ClusterIP
  ports:
    - port: 15219
      targetPort: http-web
      protocol: TCP
      name: http-web
    - port: 15220
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 15222
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/name: hub
    app.kubernetes.io/instance: hub
