// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kobsio/kobs/pkg/kube/clients/user/clientset/versioned/typed/user/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKobsV1 struct {
	*testing.Fake
}

func (c *FakeKobsV1) Users(namespace string) v1.UserInterface {
	return &FakeUsers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKobsV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
