---
apiVersion: kobs.io/v1
kind: Application
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  links:
    - title: Website
      link: https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html
    - title: GitHub
      link: https://github.com/elastic/cloud-on-k8s
    - title: Application CR
      link: https://github.com/kobsio/kobs/blob/main/deploy/demo/elastic-system/elastic-operator-application.yaml
  preview:
    title: All Logs
    plugin:
      name: elasticsearch
      options:
        query: "kubernetes.namespace: elastic-system AND kubernetes.labels.control-plane: elastic-operator"
