---
apiVersion: kobs.io/v1
kind: Application
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  links:
    - title: Website
      link: https://www.elastic.co/de/elasticsearch/
    - title: GitHub
      link: https://github.com/elastic/elasticsearch
    - title: Application CR
      link: https://github.com/kobsio/kobs/blob/main/deploy/demo/elastic-system/elasticsearch-application.yaml
  topology:
    dependencies:
      - name: elastic-operator
        namespace: elastic-system
        description: The Elasticsearch Cluster is managed by the Elastic Operator
      - name: filebeat
        namespace: elastic-system
        description: Filebeat is responsible for sending the Logs of all Containers to Elasticsearch
  preview:
    title: All Logs
    plugin:
      name: elasticsearch
      options:
        query: "kubernetes.namespace: elastic-system AND kubernetes.labels.app: elasticsearch"
