clusters:
  providers:
    - provider: kubeconfig
      kubeconfig:
        path: ${HOME}/.kube/config

plugins:
  resources:
    forbidden:
      - clusters:
          - "*"
        namespaces:
          - "*"
        resources:
          - "secrets"
        verbs:
          - "*"

  applications:
    topologyCacheDuration: 1m
    teamsCacheDuration: 1m
