---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kobs
  namespace: kobs
  labels:
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
data:
  config.yaml: |
    clusters:
      providers:
        - provider: incluster
          incluster:
            name: kobs-demo

    plugins:
      prometheus:
        - name: prometheus
          displayName: Prometheus
          description: "From metrics to insight: Power your metrics and alerting with a leading open-source monitoring solution."
          address: http://prometheus.istio-system.svc.cluster.local:9090

      elasticsearch:
        - name: elasticsearch
          displayName: Elasticsearch
          description: "A distributed, RESTful search and analytics engine capable of addressing a growing number of use cases."
          address: http://elasticsearch-es-http.elastic-system.svc.cluster.local:9200

      jaeger:
        - name: jaeger
          displayName: Jaeger
          description: "Open-source, end-to-end distributed tracing: Monitor and troubleshoot transactions in complex distributed systems"
          address: http://tracing.istio-system.svc.cluster.local:80/jaeger
