---
apiVersion: kobs.io/v1
kind: Application
metadata:
  name: kobs
  namespace: kobs
spec:
  description: Kubernetes Observability Platform
  links:
    - title: Website
      link: https://kobs.io
    - title: GitHub
      link: https://github.com/kobsio/kobs
    - title: Application CR
      link: https://github.com/kobsio/kobs/blob/main/deploy/demo/kobs/kobs-application.yaml
  topology:
    dependencies:
      - name: elasticsearch
        namespace: elastic-system
        description: Elasticsearch is used to get logs for the services.
      - name: jaeger
        namespace: istio-system
        description: Jaeger is used to get traces for the services.
      - name: prometheus
        namespace: istio-system
        description: Elasticsearch is used to get metrics for the services.
  preview:
    title: All Logs
    plugin:
      name: elasticsearch
      options:
        query: 'kubernetes.namespace: kobs AND kubernetes.labels.app_kubernetes_io\\/instance: kobs'
