---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../../../kustomize/hub
  # - ../../../kustomize/satellite
  - crs/applications
  - crs/dashboards
  - crs/teams
  - hub-gateway.yaml
  - hub-virtualservice.yaml
  - kobs-ns.yaml
