---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../kustomize/kobs
  - dashboards/istio-http.yaml
  - dashboards/istio-logs.yaml
  - dashboards/resource-usage.yaml
  - dashboards/resources.yaml
  - dashboards/traces.yaml
  - teams/team-call-of-duty.yaml
  - teams/team-diablo.yaml
  - teams/team-resident-evil.yaml
  - kobs-application.yaml
  - kobs-gateway.yaml
  - kobs-ns.yaml
  - kobs-virtualservice.yaml
patchesStrategicMerge:
  - kobs-cm.yaml
