---
apiVersion: v1
kind: ConfigMap
metadata:
  name: satellite
  namespace: kobs
  labels:
    app.kubernetes.io/name: satellite
    app.kubernetes.io/instance: satellite
data:
  config.yaml: |
    clusters:
      providers:
        - provider: incluster
          incluster:
            name: kobs

    plugins:
      - name: rss
        type: rss
      - name: opsgenie
        type: opsgenie
        options:
          apiKey: <API-KEY>
          apiURL: api.eu.opsgenie.com
          permissionsEnabled: false
        frontendOptions:
          url: https://kobs.app.eu.opsgenie.com
      - name: prometheus
        type: prometheus
        options:
          address: http://prometheus.istio-system.svc.cluster.local:9090
      - name: elasticsearch
        type: elasticsearch
        options:
          address: http://elasticsearch-es-http.elastic-system.svc.cluster.local:9200
      - name: jaeger
        type: jaeger
        options:
          address: http://tracing.istio-system.svc.cluster.local:80/jaeger
        frontendOptions:
          address: https://jaeger.kobs.io
      - name: kiali
        type: kiali
        options:
          address: http://kiali.istio-system.svc.cluster.local:20001
