// Code generated by mockery v2.12.3. DO NOT EDIT.

package instance

import (
	context "context"
	http "net/http"

	jira "github.com/andygrunwald/go-jira"

	mock "github.com/stretchr/testify/mock"
)

// MockInstance is an autogenerated mock type for the Instance type
type MockInstance struct {
	mock.Mock
}

// GetIssues provides a mock function with given fields: ctx, token, jql, startAt, maxResults
func (_m *MockInstance) GetIssues(ctx context.Context, token *Token, jql string, startAt int, maxResults int) ([]jira.Issue, int, error) {
	ret := _m.Called(ctx, token, jql, startAt, maxResults)

	var r0 []jira.Issue
	if rf, ok := ret.Get(0).(func(context.Context, *Token, string, int, int) []jira.Issue); ok {
		r0 = rf(ctx, token, jql, startAt, maxResults)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jira.Issue)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, *Token, string, int, int) int); ok {
		r1 = rf(ctx, token, jql, startAt, maxResults)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *Token, string, int, int) error); ok {
		r2 = rf(ctx, token, jql, startAt, maxResults)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetName provides a mock function with given fields:
func (_m *MockInstance) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetProjects provides a mock function with given fields: ctx, token
func (_m *MockInstance) GetProjects(ctx context.Context, token *Token) (*jira.ProjectList, error) {
	ret := _m.Called(ctx, token)

	var r0 *jira.ProjectList
	if rf, ok := ret.Get(0).(func(context.Context, *Token) *jira.ProjectList); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jira.ProjectList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *Token) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSelf provides a mock function with given fields: ctx, token
func (_m *MockInstance) GetSelf(ctx context.Context, token *Token) (*jira.User, error) {
	ret := _m.Called(ctx, token)

	var r0 *jira.User
	if rf, ok := ret.Get(0).(func(context.Context, *Token) *jira.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jira.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *Token) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetURL provides a mock function with given fields:
func (_m *MockInstance) GetURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TokenFromCookie provides a mock function with given fields: r
func (_m *MockInstance) TokenFromCookie(r *http.Request) (*Token, error) {
	ret := _m.Called(r)

	var r0 *Token
	if rf, ok := ret.Get(0).(func(*http.Request) *Token); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenToCookie provides a mock function with given fields: token
func (_m *MockInstance) TokenToCookie(token *Token) (*http.Cookie, error) {
	ret := _m.Called(token)

	var r0 *http.Cookie
	if rf, ok := ret.Get(0).(func(*Token) *http.Cookie); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Cookie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Token) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewMockInstanceT interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInstance creates a new instance of MockInstance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInstance(t NewMockInstanceT) *MockInstance {
	mock := &MockInstance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
