{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hub.fullname" . }}
  labels:
    {{- include "hub.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hub.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- toYaml .Values.networkPolicy.ingressRules | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egressRules | nindent 4 }}
{{- end }}
