---
apiVersion: v1
kind: ConfigMap
metadata:
  name: satellite
  namespace: kobs
  labels:
    app.kubernetes.io/name: satellite
    app.kubernetes.io/instance: satellite
data:
  config.yaml: |
    clusters:
      providers:
        - provider: incluster
          incluster:
            name: kobs
