---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite
  namespace: kobs
  labels:
    app.kubernetes.io/name: satellite
    app.kubernetes.io/instance: satellite
spec:
  replicas:
  selector:
    matchLabels:
      app.kubernetes.io/name: satellite
      app.kubernetes.io/instance: satellite
  template:
    metadata:
      labels:
        app.kubernetes.io/name: satellite
        app.kubernetes.io/instance: satellite
    spec:
      serviceAccountName: satellite
      containers:
        - name: satellite
          image: "kobsio/kobs:v0.10.0"
          imagePullPolicy: IfNotPresent
          args:
            - satellite
            - --log.format=console
            - --log.level=info
          env:
            - name: KOBS_SATELLITE_TOKEN
              value: unsecuretoken
          ports:
            - name: http-api
              containerPort: 15221
              protocol: TCP
            - name: http-metrics
              containerPort: 15222
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http-api
          readinessProbe:
            httpGet:
              path: /api/health
              port: http-api
          volumeMounts:
            - name: config
              mountPath: /kobs/config.yaml
              subPath: config.yaml
              readOnly: true
      terminationGracePeriodSeconds: 90
      volumes:
        - name: config
          configMap:
            name: satellite
