---
apiVersion: v1
kind: Service
metadata:
  name: satellite
  namespace: kobs
  labels:
    app.kubernetes.io/name: satellite
    app.kubernetes.io/instance: satellite
spec:
  type: ClusterIP
  ports:
    - port: 15221
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 15222
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/name: satellite
    app.kubernetes.io/instance: satellite
