{{- if .Values.watcher.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kobs.fullname" . }}-watcher
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kobs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: watcher
  template:
    metadata:
      labels:
        {{- include "kobs.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: watcher
        {{- with .Values.watcher.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/watcher/configmap.yaml") . | sha256sum }}
        {{- with .Values.watcher.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.watcher.podSecurityContext | nindent 8 }}
      containers:
        - name: watcher
          securityContext:
            {{- toYaml .Values.watcher.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - watcher
          {{- with .Values.watcher.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.watcher.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-metrics
              containerPort: 15222
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-metrics
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http-metrics
            failureThreshold: 3
          resources:
            {{- toYaml .Values.watcher.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /kobs/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- if .Values.watcher.volumeMounts }}
            {{- toYaml .Values.watcher.volumeMounts | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 90
      volumes:
        - name: config
          configMap:
            name: {{ include "kobs.fullname" . }}-watcher
        {{- if .Values.watcher.volumes }}
        {{- toYaml .Values.watcher.volumes | nindent 8 }}
        {{- end }}
      {{- with .Values.watcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watcher.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
