{{- if .Values.watcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobs.fullname" . }}-watcher
  labels:
    {{- include "kobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: watcher
    {{- with .Values.watcher.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.watcher.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.watcher.service.type }}
  ports:
    - port: 15222
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "kobs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: watcher
{{- end }}
