---
apiVersion: kobs.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: observability
spec:
  details:
    description: Open source, end-to-end distributed tracing to monitor and troubleshoot transactions in complex distributed systems.
    links:
      - title: Website
        link: https://www.jaegertracing.io
      - title: GitHub
        link: https://github.com/jaegertracing/jaeger
      - title: Application CR
        link: https://github.com/kobsio/kobs/blob/main/deploy/demo/observability/jaeger-application.yaml
    plugin:
      name: Elasticsearch
      elasticsearch:
        queries:
          - name: All Logs
            query: "kubernetes.namespace: observability AND kubernetes.labels.app: jaeger"
  resources:
    - kinds: ["deployments", "pods"]
      selector: app=jaeger
  plugins:
    - name: Elasticsearch
      elasticsearch:
        queries:
          - name: All Logs
            query: "kubernetes.namespace: observability AND kubernetes.labels.app: jaeger"
