---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobs
  namespace: observability
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "15221"
    spec:
      containers:
        - name: kobs
          image: localhost:5000/kobs:dev # "kobsio/kobs:0.1.0"
          imagePullPolicy: Always
          env:
            - name: KOBS_CLUSTERS_CACHE_DURATION_NAMESPACES
              value: 1m
            - name: KOBS_CLUSTERS_CACHE_DURATION_TOPOLOGY
              value: 1m

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kobs
  namespace: observability
  labels:
    app.kubernetes.io/name: kobs
    app.kubernetes.io/instance: kobs
data:
  config.yaml: |
    clusters:
      providers:
        - provider: incluster
          incluster:
            name: kobs-demo

    prometheus:
      - name: Prometheus
        description: Prometheus can be used for the metrics of your application.
        address: http://prometheus:9090

    elasticsearch:
      - name: Elasticsearch
        description: Elasticsearch can be used for the logs of your application.
        address: http://elasticsearch-es-http:9200

    jaeger:
      - name: Jaeger
        description: Jaeger can be used for the traces of your application.
        address: http://tracing:80/jaeger
