---
apiVersion: kobs.io/v1alpha1
kind: Application
metadata:
  name: kobs
  namespace: observability
spec:
  details:
    description: Kubernetes Observability Platform
    links:
      - title: Website
        link: https://kobs.io
      - title: GitHub
        link: https://github.com/kobsio/kobs
      - title: Application CR
        link: https://github.com/kobsio/kobs/blob/main/deploy/demo/observability/kobs-application.yaml
    plugin:
      name: Elasticsearch
      elasticsearch:
        queries:
          - name: All Logs
            query: 'kubernetes.namespace: observability AND kubernetes.labels.app_kubernetes_io\\/instance: kobs'
  resources:
    - kinds: ["deployments", "pods"]
      selector: app.kubernetes.io/name=kobs
  dependencies:
    - name: elasticsearch
      namespace: observability
      description: Elasticsearch is used to get logs for the services.
    - name: jaeger
      namespace: observability
      description: Jaeger is used to get traces for the services.
    - name: prometheus
      namespace: observability
      description: Elasticsearch is used to get metrics for the services.
  plugins:
    - name: Elasticsearch
      elasticsearch:
        queries:
          - name: All Logs
            query: 'kubernetes.namespace: observability AND kubernetes.labels.app_kubernetes_io\\/instance: kobs'
