---
apiVersion: kobs.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: observability
spec:
  details:
    description: From metrics to insight. Power your metrics and alerting with a leading open-source monitoring solution.
    links:
      - title: Website
        link: https://prometheus.io
      - title: GitHub
        link: https://github.com/prometheus/prometheus
      - title: Application CR
        link: https://github.com/kobsio/kobs/blob/main/deploy/demo/observability/prometheus-application.yaml
    plugin:
      name: Elasticsearch
      elasticsearch:
        queries:
          - name: All Logs
            query: "kubernetes.namespace: observability AND kubernetes.labels.app: prometheus"
  resources:
    - kinds: ["deployments", "pods"]
      selector: app=prometheus
  plugins:
    - name: Elasticsearch
      elasticsearch:
        queries:
          - name: All Logs
            query: "kubernetes.namespace: observability AND kubernetes.labels.app: prometheus"
