---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: bookinfo
  labels:
    app: ratings
    service: ratings
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: ratings

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  namespace: bookinfo
  labels:
    account: ratings

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  namespace: bookinfo
  labels:
    app: ratings
    version: v1
  annotations:
    kobs.io/dashboards: |
      [
        {
          "name": "istio-http",
          "namespace": "kobs",
          "title": "Istio HTTP Metrics",
          "placeholders": {
            "namespace": "<% $.metadata.namespace %>",
            "app": "ratings"
          }
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
      annotations:
        kobs.io/dashboards: |
          [
            {
              "name": "resource-usage",
              "namespace": "kobs",
              "title": "Resource Usage",
              "placeholders": {
                "namespace": "<% $.metadata.namespace %>",
                "pod": "<% $.metadata.name %>"
              }
            }
          ]
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
        - name: ratings
          image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          resources: {}
          securityContext:
            runAsUser: 1000
