---
apiVersion: kobs.io/v1beta1
kind: Application
metadata:
  name: reviews
  namespace: bookinfo
spec:
  description: The reviews microservice contains book reviews. It also calls the ratings microservice.
  links:
    - title: Website
      link: https://istio.io/latest/docs/examples/bookinfo/
    - title: GitHub
      link: https://github.com/istio/istio/tree/master/samples/bookinfo
    - title: Application CR
      link: https://github.com/kobsio/kobs/blob/main/deploy/demo/bookinfo/reviews-application.yaml
  teams:
    - name: team-resident-evil
      namespace: kobs
  dependencies:
    - name: ratings
      description: Get book ranking information.
  preview:
    title: Incoming Success Rate
    plugin:
      name: prometheus
      options:
        unit: "%"
        queries:
          - query: sum(irate(istio_requests_total{reporter="destination",destination_workload_namespace=~"bookinfo",destination_workload=~"reviews-.*",response_code!~"5.*"}[5m])) / sum(irate(istio_requests_total{reporter="destination",destination_workload_namespace=~"bookinfo",destination_workload=~"reviews-.*"}[5m])) * 100
  dashboards:
    - name: resources
      namespace: kobs
      title: Resources in the bookinfo namespace
      placeholders:
        namespace: bookinfo
    - name: resource-usage
      namespace: kobs
      title: Resource Usage
      placeholders:
        namespace: bookinfo
        pod: "reviews-.*-.*-.*"
    - name: istio-http
      namespace: kobs
      title: Istio HTTP Metrics
      placeholders:
        namespace: bookinfo
        app: reviews
    - name: istio-logs
      namespace: kobs
      title: Istio Logs
      placeholders:
        namespace: bookinfo
        app: reviews
    - name: traces
      namespace: kobs
      title: Traces
      placeholders:
        service: reviews.bookinfo
