// Code generated by MockGen. DO NOT EDIT.
// Source: virtualmachinescalesets.go

// Package virtualmachinescalesets is a generated GoMock package.
package virtualmachinescalesets

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ListVirtualMachineScaleSets mocks base method.
func (m *MockClient) ListVirtualMachineScaleSets(ctx context.Context, resourceGroup string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVirtualMachineScaleSets", ctx, resourceGroup)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVirtualMachineScaleSets indicates an expected call of ListVirtualMachineScaleSets.
func (mr *MockClientMockRecorder) ListVirtualMachineScaleSets(ctx, resourceGroup interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVirtualMachineScaleSets", reflect.TypeOf((*MockClient)(nil).ListVirtualMachineScaleSets), ctx, resourceGroup)
}

// ListVirtualMachines mocks base method.
func (m *MockClient) ListVirtualMachines(ctx context.Context, resourceGroup, virtualMachineScaleSet string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVirtualMachines", ctx, resourceGroup, virtualMachineScaleSet)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVirtualMachines indicates an expected call of ListVirtualMachines.
func (mr *MockClientMockRecorder) ListVirtualMachines(ctx, resourceGroup, virtualMachineScaleSet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVirtualMachines", reflect.TypeOf((*MockClient)(nil).ListVirtualMachines), ctx, resourceGroup, virtualMachineScaleSet)
}
