// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ElasticsearchClient is the client API for Elasticsearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ElasticsearchClient interface {
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
}

type elasticsearchClient struct {
	cc grpc.ClientConnInterface
}

func NewElasticsearchClient(cc grpc.ClientConnInterface) ElasticsearchClient {
	return &elasticsearchClient{cc}
}

func (c *elasticsearchClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, "/plugins.elasticsearch.Elasticsearch/GetLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ElasticsearchServer is the server API for Elasticsearch service.
// All implementations must embed UnimplementedElasticsearchServer
// for forward compatibility
type ElasticsearchServer interface {
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	mustEmbedUnimplementedElasticsearchServer()
}

// UnimplementedElasticsearchServer must be embedded to have forward compatible implementations.
type UnimplementedElasticsearchServer struct {
}

func (UnimplementedElasticsearchServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedElasticsearchServer) mustEmbedUnimplementedElasticsearchServer() {}

// UnsafeElasticsearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ElasticsearchServer will
// result in compilation errors.
type UnsafeElasticsearchServer interface {
	mustEmbedUnimplementedElasticsearchServer()
}

func RegisterElasticsearchServer(s grpc.ServiceRegistrar, srv ElasticsearchServer) {
	s.RegisterService(&Elasticsearch_ServiceDesc, srv)
}

func _Elasticsearch_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElasticsearchServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.elasticsearch.Elasticsearch/GetLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElasticsearchServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Elasticsearch_ServiceDesc is the grpc.ServiceDesc for Elasticsearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Elasticsearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.elasticsearch.Elasticsearch",
	HandlerType: (*ElasticsearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogs",
			Handler:    _Elasticsearch_GetLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "elasticsearch.proto",
}
