name: Continuous Integration

on:
  push:
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'cmd/kobs/Dockerfile'
      - 'deploy/**'
      - 'docs/**'
      - 'hack/**'
      - '.dockerignore'
      - '.editorconfig'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'mkdocs.yml'
      - 'README.md'

jobs:
  go:
    name: Go
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Dependencies
        run: |
          go mod download

      - name: Test
        run: |
          make test-coverage
          cat coverage.out | grep -v "github.com/kobsio/kobs/pkg/kube/apis" | grep -v "github.com/kobsio/kobs/pkg/kube/clients" | grep -v "_mock.go" > coverage_modified.out; mv coverage_modified.out coverage.out

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out

      - name: Build
        run: |
          make build

  node:
    name: Node.js
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          yarn install

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build
