name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --config=./.github/golangci.yaml
          skip-cache: true

      - name: Test
        run: |
          make test-coverage
          cat coverage.out | grep -v "github.com/kobsio/kobs/pkg/cluster/kubernetes/apis" | grep -v "github.com/kobsio/kobs/pkg/cluster/kubernetes/clients" | grep -v "_mock.go" > coverage_modified.out; mv coverage_modified.out coverage.out

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: go
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out

      - name: Build
        run: |
          make build

  node:
    name: Node.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin:
          - app
          - azure
          - core
          - datadog
          - elasticsearch
          - flux
          - github
          - grafana
          - harbor
          - helm
          - jaeger
          - jira
          - kiali
          - klogs
          - mongodb
          - opsgenie
          - prometheus
          - rss
          - runbooks
          - signalsciences
          - sonarqube
          - sql
          - techdocs
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install Dependencies
        run: |
          npm clean-install

      - name: Lint
        run: |
          npm run lint --workspace=@kobsio/${{ matrix.plugin }}

      - name: Test
        run: |
          npm run test:coverage --workspace=@kobsio/${{ matrix.plugin }}

      - name: Upload Coverage "packages/app"
        uses: codecov/codecov-action@v3
        with:
          flags: node-${{ matrix.plugin }}
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: app/packages/${{ matrix.plugin }}/coverage

      - name: Build
        if: ${{ matrix.plugin == 'app' }}
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          npm run build
