# name: Helm

# on:
#   push:
#     paths:
#       - '.github/workflows/helm.yaml'
#       - 'deploy/helm/**'

# jobs:
#   helm:
#     name: Helm Chart
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         chart: [hub, satellite]
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Lint
#         run: |
#           helm lint deploy/helm/${{ matrix.chart }}

#       - name: Template
#         run: |
#           helm template kobs-${{ matrix.chart }} -n kobs deploy/helm/${{ matrix.chart }}

#       - name: Install
#         run: |
#           kind create cluster
#           sleep 60s
#           kubectl create namespace kobs
#           sleep 10s
#           helm install --namespace kobs kobs${{ matrix.chart }} deploy/helm/${{ matrix.chart }}

#       - name: Configure SSH
#         if: ${{ github.ref == 'refs/heads/main' }}
#         uses: webfactory/ssh-agent@v0.5.1
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Configure Git
#         if: ${{ github.ref == 'refs/heads/main' }}
#         run: |
#           git config --global user.email "admin@kobs.io" && git config --global user.name "kobsio"

#       - name: Package Helm Chart
#         if: ${{ github.ref == 'refs/heads/main' }}
#         run: |
#           helm package ./deploy/helm/${{ matrix.chart }}

#       - name: Clone Helm Repository
#         if: ${{ github.ref == 'refs/heads/main' }}
#         run: |
#           git clone git@github.com:kobsio/helm-repository.git

#       - name: Update Helm Repository
#         if: ${{ github.ref == 'refs/heads/main' }}
#         run: |
#           mv ${{ matrix.chart }}* ./helm-repository/ && helm repo index helm-repository/ --url https://helm.kobs.io/

#       - name: Commit Changes
#         if: ${{ github.ref == 'refs/heads/main' }}
#         run: |
#           cd helm-repository/ && git add . && git commit -m "Add new release for kobs ${{ matrix.chart }}"

#       - name: Push Changes
#         if: ${{ github.ref == 'refs/heads/main' }}
#         run: |
#           cd helm-repository/ && git push
