---
apiVersion: kobs.io/v1
kind: Application
metadata:
  name: prometheus
  namespace: istio-system
spec:
  description: From metrics to insight. Power your metrics and alerting with a leading open-source monitoring solution.
  links:
    - title: Website
      link: https://prometheus.io
    - title: GitHub
      link: https://github.com/prometheus/prometheus
    - title: Application CR
      link: https://github.com/kobsio/kobs/blob/main/deploy/demo/prometheus/prometheus-application.yaml
  preview:
    title: All Logs
    plugin:
      name: elasticsearch
      options:
        query: "kubernetes.namespace: istio-system AND kubernetes.labels.app: prometheus"
